#######################################################################################################################
# Application
#######################################################################################################################
app:
  name: Voyage
  contact-support:
    email: support@LighthouseSoftware.com
    phone: 651-888-6021
    website: http://LighthouseSoftware.com/support
  default-country: US

#######################################################################################################################
# AWS Configuration to send Emails and SMS
#######################################################################################################################
cloud:
  aws:
    enabled: false
    stack:
      auto: false
    credentials:
      accessKey: ENTER YOUR CODE
      secretKey: ENTER YOUR CODE
    region:
      auto: true
      static: us-east-1
#######################################################################################################################
# Spring configuration
#######################################################################################################################
spring:

  mail:
    host: localhost
    port: 3025
    overrideAddress: testmsg@LighthouseSoftware.com

  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8
    suffix: .ftl

  autoconfigure:
      exclude:
        - org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration